name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install -v -e .[test]
    - name: Test with pytest
      run: |
        python -m pytest -v
